version: '3.7'

services:
  webapp:
    build: .
    image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
    volumes:
      - ./https:/https:ro
    networks:
      - dotnetcore-database-container_common
networks:
  dotnetcore-database-container_common:
    # driver: "bridge"
    external: true