version: "3.7"
services:
  dotnetcore-database-container:
    container_name: dotnetcore-database-container
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "0f6e883001c330bb91d708982f228d76" # local dev password
      ACCEPT_EULA: "Y"
    volumes:
      - sqlsystem:/var/opt/mssql/
      - sqldata:/var/opt/sqlserver/data
      - sqllog:/var/opt/sqlserver/log
      - sqlbackup:/var/opt/sqlserver/backup
    networks:
      - common
networks:
  common:
    driver: bridge
volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:
# default username sa